INSERT INTO tienda (nombre, tlf) VALUES ('PadelZone Crevillente', '+34600000000');

INSERT INTO producto (cod, nombre, nombre_corto, descripcion, marca, nivel, forma, peso, pvp, exclusiva, imagen) VALUES
('P001', 'Bullpadel Vertex 03', 'Vertex 03', 'Pala de potencia para jugadores avanzados', 'Bullpadel', 'avanzado', 'diamante', 365, 249.95, TRUE, NULL),
('P002', 'Adidas Adipower Control', 'Adipower Ctrl', 'Gran control y precisión en cada golpe', 'Adidas', 'avanzado', 'redonda', 360, 229.95, FALSE, NULL),
('P003', 'Head Flash', 'Head Flash', 'Ideal para jugadores principiantes', 'Head', 'principiante', 'lagrima', 355, 89.95, TRUE, NULL),
('P004', 'Nox ML10 Pro Cup', 'ML10 Pro Cup', 'Equilibrio perfecto entre potencia y control', 'Nox', 'intermedio', 'redonda', 365, 179.95, FALSE, NULL),
('P005', 'Siux Pegasus', 'Pegasus', 'Pala versátil para nivel intermedio', 'Siux', 'intermedio', 'lagrima', 362, 149.95, TRUE, NULL),
('P006', 'Babolat Technical Viper', 'Tech Viper', 'Máxima potencia para jugadores ofensivos', 'Babolat', 'avanzado', 'diamante', 370, 299.95, FALSE, NULL),
('P007', 'Wilson Blade Elite', 'Blade Elite','Control y comodidad para jugadores amateur', 'Wilson', 'principiante', 'redonda', 358, 109.95, TRUE, NULL),
('P008', 'Drop Shot Conqueror', 'Conqueror', 'Pala de alto rendimiento con gran potencia', 'Drop Shot', 'avanzado', 'diamante', 368, 269.95, TRUE, NULL),
('P009', 'Head Evo Sanyo', 'Evo Sanyo', 'Perfecta para iniciarse en el pádel', 'Head', 'principiante', 'lagrima', 360, 79.95, FALSE, NULL),
('P010', 'Adidas Drive 3.2', 'Drive 3.2', 'Control y salida de bola fácil', 'Adidas', 'principiante', 'redonda', 355, 69.95, TRUE, NULL),
('P011', 'Bullpadel Hack 03', 'Hack 03', 'Potencia extrema para jugadores expertos', 'Bullpadel', 'avanzado', 'diamante', 372, 279.95, FALSE, NULL),
('P012', 'Nox AT10 Genius', 'AT10 Genius', 'Pala equilibrada usada por profesionales', 'Nox', 'avanzado', 'lagrima', 365, 259.95, TRUE, NULL),
('P013', 'Siux Diablo Revolution', 'Diablo Rev', 'Gran versatilidad y control', 'Siux', 'intermedio', 'lagrima', 363, 199.95, FALSE, NULL),
('P014', 'Babolat Counter Veron', 'Counter Veron', 'Control y precisión para defensa', 'Babolat', 'intermedio', 'redonda', 365, 189.95, TRUE, NULL),
('P015', 'Wilson Pro Staff Elite', 'Pro Staff', 'Pala cómoda y manejable', 'Wilson', 'intermedio', 'redonda', 360, 139.95, FALSE, NULL),
('P016', 'Drop Shot Explorer', 'Explorer', 'Buen equilibrio para jugadores medios', 'Drop Shot', 'intermedio', 'lagrima', 362, 159.95, TRUE, NULL),
('P017', 'Head Delta Pro', 'Delta Pro', 'Potencia explosiva para ataque', 'Head', 'avanzado', 'diamante', 370, 289.95, TRUE, NULL),
('P018', 'Adidas Metalbone', 'Metalbone', 'Tecnología avanzada y gran potencia', 'Adidas', 'avanzado', 'diamante', 368, 299.95, FALSE, NULL),
('P019', 'Bullpadel Indiga Control', 'Indiga Ctrl', 'Perfecta para principiantes', 'Bullpadel', 'principiante', 'redonda', 355, 59.95, TRUE, NULL),
('P020', 'Nox X-One Evo', 'X-One Evo', 'Muy manejable y cómoda', 'Nox', 'principiante', 'lagrima', 360, 99.95, FALSE, NULL)
('P021', 'Bullpadel Hack 02', 'Hack 02', 'Potencia y control para nivel avanzado', 'Bullpadel', 'avanzado', 'diamante', 370, 259.95, FALSE, NULL),
('P022', 'Adidas Adipower Lite', 'Adipower Lite', 'Pala ligera para jugadores intermedios', 'Adidas', 'intermedio', 'redonda', 355, 149.95, FALSE, NULL),
('P023', 'Head Alpha Pro', 'Alpha Pro', 'Control total para principiantes avanzados', 'Head', 'principiante', 'lagrima', 358, 99.95, FALSE, NULL),
('P024', 'Nox ML10 Luxury', 'ML10 Luxury', 'Alta gama para jugadores profesionales', 'Nox', 'avanzado', 'diamante', 368, 289.95, FALSE, NULL),
('P025', 'Siux Diablo Carbon', 'Diablo Carbon', 'Fibra de carbono para máxima potencia', 'Siux', 'avanzado', 'diamante', 372, 229.95, FALSE, NULL),
('P026', 'Babolat Viper Air', 'Viper Air', 'Ultraligera para mayor velocidad', 'Babolat', 'intermedio', 'lagrima', 350, 199.95, FALSE, NULL),
('P027', 'Wilson Bela Team', 'Bela Team', 'Pala oficial del circuito profesional', 'Wilson', 'avanzado', 'redonda', 365, 219.95, FALSE, NULL),
('P028', 'Drop Shot Synergy', 'Synergy', 'Equilibrio perfecto para todos los niveles', 'Drop Shot', 'intermedio', 'lagrima', 360, 139.95, FALSE, NULL),
('P029', 'Head Graphene 360', 'Graphene 360', 'Tecnología Graphene para mayor control', 'Head', 'avanzado', 'diamante', 370, 279.95, FALSE, NULL),
('P030', 'Adidas Match Light', 'Match Light', 'Ideal para iniciarse en el pádel', 'Adidas', 'principiante', 'redonda', 350, 79.95, FALSE, NULL),
('P031', 'Bullpadel Flow', 'Flow', 'Pala versátil para nivel intermedio', 'Bullpadel', 'intermedio', 'lagrima', 362, 169.95, FALSE, NULL),
('P032', 'Nox Equation', 'Equation', 'Gran manejabilidad y control', 'Nox', 'intermedio', 'redonda', 358, 159.95, FALSE, NULL),
('P033', 'Siux Fenix', 'Fenix', 'Pala de alta gama para expertos', 'Siux', 'avanzado', 'diamante', 370, 249.95, FALSE, NULL),
('P034', 'Babolat Technical Veron Air', 'Veron Air', 'Ligera y potente para atacantes', 'Babolat', 'avanzado', 'diamante', 365, 269.95, FALSE, NULL),
('P035', 'Wilson Ultra Control', 'Ultra Control', 'Máximo control para defensores', 'Wilson', 'intermedio', 'redonda', 362, 179.95, FALSE, NULL),
('P036', 'Drop Shot Conqueror Soft', 'Conqueror Soft', 'Núcleo suave para mayor confort', 'Drop Shot', 'principiante', 'lagrima', 355, 89.95, FALSE, NULL),
('P037', 'Head Delta Elite', 'Delta Elite', 'Para jugadores que buscan potencia', 'Head', 'avanzado', 'diamante', 372, 239.95, FALSE, NULL),
('P038', 'Adidas Adipower Junior', 'Adipower Junior', 'Perfecta para jugadores jóvenes', 'Adidas', 'principiante', 'redonda', 340, 59.95, FALSE, NULL),
('P039', 'Bullpadel Comfort', 'Comfort', 'Máxima comodidad para largas sesiones', 'Bullpadel', 'principiante', 'redonda', 352, 69.95, FALSE, NULL),
('P040', 'Nox Tempo', 'Tempo', 'Pala de iniciación con gran salida de bola', 'Nox', 'principiante', 'lagrima', 355, 74.95, FALSE, NULL);

INSERT INTO stock (producto, tienda, unidades) VALUES
('P001', 1, 5),
('P002', 1, 8),
('P003', 1, 12),
('P004', 1, 6),
('P005', 1, 9),
('P006', 1, 3),
('P007', 1, 15),
('P008', 1, 4),
('P009', 1, 10),
('P010', 1, 20),
('P011', 1, 2),
('P012', 1, 7),
('P013', 1, 11),
('P014', 1, 6),
('P015', 1, 8),
('P016', 1, 9),
('P017', 1, 3),
('P018', 1, 5),
('P019', 1, 14),
('P020', 1, 10)
('P021', 1, 6),
('P022', 1, 8),
('P023', 1, 10),
('P024', 1, 4),
('P025', 1, 5),
('P026', 1, 7),
('P027', 1, 3),
('P028', 1, 9),
('P029', 1, 4),
('P030', 1, 15),
('P031', 1, 8),
('P032', 1, 6),
('P033', 1, 3),
('P034', 1, 5),
('P035', 1, 7),
('P036', 1, 12),
('P037', 1, 4),
('P038', 1, 20),
('P039', 1, 14),
('P040', 1, 10);;

-- =========================
-- TABLA: carrito (ejecutar después de crear la tabla)
-- =========================
CREATE TABLE IF NOT EXISTS carrito (
    id INT AUTO_INCREMENT PRIMARY KEY,
    usuario VARCHAR(100) NOT NULL,
    producto VARCHAR(12) NOT NULL,
    unidades INT DEFAULT 1,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (producto) REFERENCES producto(cod)
);