INSERT INTO producto (cod, nombre, nombre_corto, descripcion, marca, nivel, forma, peso, pvp, oferta) VALUES
('P001', 'Bullpadel Vertex 03', 'Vertex 03', 'Pala de potencia para jugadores avanzados', 'Bullpadel', 'avanzado', 'diamante', 365, 249.95, TRUE),
('P002', 'Adidas Adipower Control', 'Adipower Ctrl', 'Gran control y precisión en cada golpe', 'Adidas', 'avanzado', 'redonda', 360, 229.95, FALSE),
('P003', 'Head Flash', 'Head Flash', 'Ideal para jugadores principiantes', 'Head', 'principiante', 'lagrima', 355, 89.95, TRUE),
('P004', 'Nox ML10 Pro Cup', 'ML10 Pro Cup', 'Equilibrio perfecto entre potencia y control', 'Nox', 'intermedio', 'redonda', 365, 179.95, FALSE),
('P005', 'Siux Pegasus', 'Pegasus', 'Pala versátil para nivel intermedio', 'Siux', 'intermedio', 'lagrima', 362, 149.95, TRUE),
('P006', 'Babolat Technical Viper', 'Tech Viper', 'Máxima potencia para jugadores ofensivos', 'Babolat', 'avanzado', 'diamante', 370, 299.95, FALSE),
('P007', 'Wilson Blade Elite', 'Blade Elite', 'Control y comodidad para jugadores amateur', 'Wilson', 'principiante', 'redonda', 358, 109.95, TRUE),
('P008', 'Drop Shot Conqueror', 'Conqueror', 'Pala de alto rendimiento con gran potencia', 'Drop Shot', 'avanzado', 'diamante', 368, 269.95, TRUE),
('P009', 'Head Evo Sanyo', 'Evo Sanyo', 'Perfecta para iniciarse en el pádel', 'Head', 'principiante', 'lagrima', 360, 79.95, FALSE),
('P010', 'Adidas Drive 3.2', 'Drive 3.2', 'Control y salida de bola fácil', 'Adidas', 'principiante', 'redonda', 355, 69.95, TRUE),
('P011', 'Bullpadel Hack 03', 'Hack 03', 'Potencia extrema para jugadores expertos', 'Bullpadel', 'avanzado', 'diamante', 372, 279.95, FALSE),
('P012', 'Nox AT10 Genius', 'AT10 Genius', 'Pala equilibrada usada por profesionales', 'Nox', 'avanzado', 'lagrima', 365, 259.95, TRUE),
('P013', 'Siux Diablo Revolution', 'Diablo Rev', 'Gran versatilidad y control', 'Siux', 'intermedio', 'lagrima', 363, 199.95, FALSE),
('P014', 'Babolat Counter Veron', 'Counter Veron', 'Control y precisión para defensa', 'Babolat', 'intermedio', 'redonda', 365, 189.95, TRUE),
('P015', 'Wilson Pro Staff Elite', 'Pro Staff', 'Pala cómoda y manejable', 'Wilson', 'intermedio', 'redonda', 360, 139.95, FALSE),
('P016', 'Drop Shot Explorer', 'Explorer', 'Buen equilibrio para jugadores medios', 'Drop Shot', 'intermedio', 'lagrima', 362, 159.95, TRUE),
('P017', 'Head Delta Pro', 'Delta Pro', 'Potencia explosiva para ataque', 'Head', 'avanzado', 'diamante', 370, 289.95, TRUE),
('P018', 'Adidas Metalbone', 'Metalbone', 'Tecnología avanzada y gran potencia', 'Adidas', 'avanzado', 'diamante', 368, 299.95, FALSE),
('P019', 'Bullpadel Indiga Control', 'Indiga Ctrl', 'Perfecta para principiantes', 'Bullpadel', 'principiante', 'redonda', 355, 59.95, TRUE),
('P020', 'Nox X-One Evo', 'X-One Evo', 'Muy manejable y cómoda', 'Nox', 'principiante', 'lagrima', 360, 99.95, FALSE);